### ISSUE TITLE
Hard coded path in library

### ISSUE THREAD

**Issue by ckmaresca** [Flynsarmy/Slim-Monolog#11]
There is a hard-coded log location at line 110: https://github.com/Flynsarmy/Slim-Monolog/blob/master/Log/MonologWriter.php#L110 

`new \Monolog\Handler\StreamHandler('./logs/'.date('y-m-d').'.log'),`

Since this hard coded location merges into the other locations array, it could easily cause a lot of problems in light-weight situations (like docker containers) which have virtually no disk space and do all their logging remotely.   It also destroys one of the most valuable things about Monolog, that you have fine, granular control over where the logs go.

It really should be `'handlers' => array(),`

Worse yet, because this merge is silent & undocumented, it took me about 3 hours to track this down as I didn't have a directory in "." called "logs".....

**Comment by Flynsarmy** [comment]
PRs accepted :)

**Comment by ckmaresca** [comment]
Sorry, no time to setup a fork.  It's a 5 second fix on your end and a 30 minute fix for me to setup a fork etc.  Literally delete 1 line of code, it's take 10x the time for me to write this up than it would for you to fix it.
