### ISSUE TITLE
Monolog throws error because of constructor

### ISSUE THREAD

**Issue by bladi87** [Flynsarmy/Slim-Monolog#8]
Monolog, as of 1.15.0, tries to create a dir on every log action and raises an exception: https://github.com/Seldaek/monolog/blob/6dd76b944d42d7b27bb3d09cd0f6fa88a80817f5/src/Monolog/Handler/StreamHandler.php#L51

Slim-Monolog creates an unused monolog instance with an invalid log dir in its constructor: https://github.com/Flynsarmy/Slim-Monolog/blob/master/Log/MonologWriter.php#L108

So applications with Monolog 1.15.0 and Slim-Monolog won't work now, I think.

**Comment by Flynsarmy** [comment]
I don't use slim framework anymore. Please send a PR to fix.

**Comment by bladi87** [comment]
PR: https://github.com/Flynsarmy/Slim-Monolog/pull/9

**Comment by Flynsarmy** [comment]
Merged.
